<a href="https://colab.research.google.com/github/helya02/PCA/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
def data_mean(data):
  sum = data.sum(axis = 0)
  num = data.shape[1]
  return  sum / num




In [ ]:
def mean_deviation_matrix(data):

  return data - data_mean(data)



In [ ]:
def cov_matrix(data):
  X_meaned =mean_deviation_matrix(data)
  cov_mat = np.cov(X_meaned , rowvar = False)
  return cov_mat



In [ ]:
def eigen(covariance_matrix):
          return np.linalg.eig(covariance_matrix)


def PCA(matrix , n):
  covariance_matrix  = cov_matrix(matrix)
  eigenvalues, eigenvectors = eigen(covariance_matrix)

  eig_pairs = [(np.abs(np.array(eigenvalues[i])), np.array(eigenvectors[:,i])) for i in range(len(eigenvalues))]
  sorted_ = sorted(eig_pairs, reverse = True)

  W = []

  for i in range(n):
    W.append(sorted_[i][1].reshape((len(eigenvectors),1)))

  X_meaned = mean_deviation_matrix(matrix)

  matrix_w = np.hstack(W[::])

  print(matrix_w)

  X_reduced = np.dot(matrix_w.transpose() , X_meaned.transpose() ).transpose()

  return X_reduced



In [ ]:
dataset = pd.read_csv("iris.csv")

features = np.array(dataset.drop(['variety'], axis = 1))


pca = PCA(features,3)

print(pca.shape)


[[ 0.36138659 -0.65658877 -0.58202985]
 [-0.08452251 -0.73016143  0.59791083]
 [ 0.85667061  0.17337266  0.07623608]
 [ 0.3582892   0.07548102  0.54583143]]
(150, 3)
